### ISSUE TITLE
Major differences between  panelcn.MOPS  and cn.MOPS?

### ISSUE THREAD

**Issue by xiucz** [bioinf-jku/panelcn.mops#12]
Hi, 

Could you tell us the major differences between panelcn.MOPS and cn.MOPS?

Thanks a lot.
 Xiucz

**Comment by saanasum** [comment]
panelcn.MOPS is for CNV detection using panel-based NGS data (as for example TSC-94 panel data) while cn.MOPS is for CNV detection using WES or WGS data.

**Comment by gpovysil** [comment]
In addition panelcn.MOPS is tuned for a diagnostic setting meaning that the default settings ensure high sensitivity. For the same reason, it also includes several QC metrics. panelcn.MOPS only detects copy numers (CN) 0-4 (homozygous and heterozygous deletion, normal CN2, heterozygous and homozygous duplication), whereas cn.MOPS can also detect higher CNs. panelcn.MOPS does not include a segmentation step so that it is able to detect single exon CNVs or even smaller ones.

If you need further information, let me know.

**Comment by xiucz** [comment]
@saanasum @gpovysil  Thank you, I have got the general idea of the differences. For more information, I will read the paper.
