### ISSUE TITLE
Only getting NAs in resultstable.

### ISSUE THREAD

**Issue by Luker121** [bioinf-jku/panelcn.mops#18]
Hi,
I am a master student and I am using panelcn.mops to detect CNVs from whole genome data by comparing cases vs controls. In this case I have one control and want to compare it to one sample. For this, I am using the Agilent V6 bed file, which I downloaded from SureDesigns. For my purpose I would like to get the CNVs from the whole genome data, not only from a specific gene region. 
But when running the runpanelcnmops command:
`runPanelcnMops(test, countWindows=countWindows, minMedianRC=0)`
I get this information:

`All genes selected.
Analyzing sample(s) sample.bam

new sampleThresh 74.25
Had to reduce read counts for exon HRNR.NM_001009931.ens|ENST00000420707.ens|ENST00000593011.ens|ENST00000368801.ccds|CCDS30859
Had to reduce read counts for exon MUC4.NM_018406.NM_001322468.NM_138297.NM_004532.ens|ENST00000349607.ens|ENST00000346145.ens|ENST00000478156.ens|ENST00000466475.ens|ENST00000477756.ens|ENST00000475231.ens|ENST00000479406.ens|ENST00000470451.ens|ENST00000480843.ens|ENST00000462323.ens|ENST00000477086.ens|ENST00000463781.ccds|CCDS54700.ccds|CCDS3311.ccds|CCDS3310
Had to reduce read counts for exon MUC4.NM_018406.NM_001322468.NM_138297.NM_004532.ens|ENST00000349607.ens|ENST00000346145.ens|ENST00000478156.ens|ENST00000466475.ens|ENST00000477756.ens|ENST00000475231.ens|ENST00000479406.ens|ENST00000470451.ens|ENST00000480843.ens|ENST00000462323.ens|ENST00000477086.ens|ENST00000463781.ccds|CCDS54700.ccds|CCDS3311.ccds|CCDS3310
Had to reduce read counts for exon MUC4.NM_018406.NM_001322468.NM_138297.NM_004532.ens|ENST00000349607.ens|ENST00000346145.ens|ENST00000478156.ens|ENST00000466475.ens|ENST00000477756.ens|ENST00000475231.ens|ENST00000479406.ens|ENST00000470451.ens|ENST00000480843.ens|ENST00000462323.ens|ENST00000477086.ens|ENST00000463781.ccds|CCDS54700.ccds|CCDS3311.ccds|CCDS3310

Ignoring X-chromosomal exons (sex is mixed/unknown).

Ignoring Y-chromosomal exons.

Analyzing sample sample.bam

"corrThresh" is set to 0.99
"maxControls" is set to 25
1
0.980450370066736

Low correlation.

Selected 1 out of 1 controls:

control.bam

Normalizing...
Too many bad control samples
0.5176383163514650.517638316351465
Bad test sample sample.bam 
Try using more controls!
Low quality exon(s):
1_12595_12802
1_15795_15914
1_16743_17098
1_17247_18121
1_18216_18411
1_18963_19169
1_65509_65726
1_65776_65972
.............`

And at the end my resultstable has only NAs like this:
`CNV regions: 
GRanges object with 22 ranges and 2 metadata columns:
       seqnames            ranges strand | sample.bam control.bam
          <Rle>         <IRanges>  <Rle> |      <logical>      <logical>
   [1]        1   12080-249231246      * |           <NA>           <NA>
   [2]        2   38821-243168976      * |           <NA>           <NA>
   [3]        3  238260-197955212      * |           <NA>           <NA>
   [4]        4   53213-191013682      * |           <NA>           <NA>
   [5]        5  140305-180899428      * |           <NA>           <NA>`

I get the same results when also using more than 10 controls. Do you know what went wrong?

Best,
Lukas

**Comment by gpovysil** [comment]
There are several problems, hard to say which one leads to the result you get:
1. I would not use panelcn.mops, but the original cn.mops (http://bioconductor.org/packages/release/bioc/html/cn.mops.html) for WGS data. The tutorial of the package should provide you all the information you need to get started. If you want to increase sensitivity, play around with the vector "I" (moving the values closer to the one that corresponds to CN2 increases sensitivity, but decreases specificity). Point 2 below is somehow relevant for cn.mops as well. You can ignore Points 3 and 4 if you switch to cn.mops.
2. panelcn.MOPS does not work with only 1 control sample.
3. You should adapt your BED file so that the 4th column has the right format. This code could work, but probably needs to be adapted:
 panel.data %>% mutate(Gene = gsub("ref\\|", "", unlist(map2(str_split(V4, ","), 
                                                 map(lapply(str_split(V4, ","), 
                                                            function(x) grep("ref", x)), last), 
                                                 function(x, y) x[y])))) %>%  
    group_by(Gene) %>% 
    mutate(Exon = paste0("E", row_number())) %>% 
    mutate(V4new = paste(Gene, Exon, V1, V2, V3, sep = "."))  
4. The object does not look like the panelcn.mops resulttable. Did you use the function createResultTable? The CNV regions slot contains NAs by default in panelcn.mops since we do not support it. 

I hope that helps.

**Comment by Luker121** [comment]
Thank you very much for the fast response and also the code for changing the bedfile. So you wouldn't recommend me to use panelcn.mops. But why? Isn't it made for exact this case?
Best,
Lukas

**Comment by gpovysil** [comment]
panelcn.mops is a modified version of cn.mops specifically for gene panel data, and might also work for WES data. cn.mops was designed for WGS so fits your needs better. The only thing that I would adapt is the sensitivity as described above.
