### ISSUE TITLE
Reporting log normalized read counts as table

### ISSUE THREAD

**Issue by saanasum** [bioinf-jku/panelcn.mops#6]
Is it possible to report also the log normalized read counts as .csv table similar to the hidden function in cn.MOPS:

`library(cn.mops)`
`data(cn.mops)`
`res <- cn.mops(XRanges)`
`logRatios <- cn.mops:::.makeLogRatios(res)`
`as.data.frame(logRatios)`

 
Many thanks for your help

**Comment by gpovysil** [comment]
You can use the cn.mops function on the items of the resultlist you get from panelcn.mops.

```
library(panelcn.mops)
data(panelcn.mops)
XandCB <- test
elementMetadata(XandCB) <- cbind(elementMetadata(XandCB), elementMetadata(control))
resultlist <- runPanelcnMops(XandCB, testiv = 1:ncol(elementMetadata(test)), countWindows = countWindows)

res <- resultlist[[1]]

logRatios <- cn.mops:::.makeLogRatios(res)
as.data.frame(logRatios[,1])
```
If you have more than 1 test sample, you just have to go over the resultlist and apply the makeLogRatios function. However, you always have to use the 1st column of the results since that's where your test sample is.

**Comment by saanasum** [comment]
It works! Thank you.
